-- STATUS: RETIRED 2026-07-31. This file declares nothing and applies nothing.
--
-- SUCCESSOR: migrations/001_lanes.sql. That file is the schema; this one is a
-- tombstone (§16, rule 20). docs/LANE-MODEL.md remains canonical for the
-- reasoning behind it, and docs/SENSITIVITY.md for the rungs.
--
-- ---------------------------------------------------------------------------
-- WHY IT WAS RETIRED
--
-- This path existed to say one thing: the DDL was written and not adopted. It
-- sat in docs/ rather than migrations/ because §18 item 3 held it behind three
-- gates -- it rested on a paraphrase of Willow's PROTECTED_AGENTS.md Part III,
-- which nobody here had opened; it was gated on blocker 2 (the disposition of
-- apps/marching-arts); and on blocker 4 (which surfaces exist).
--
-- Part III was then read at source (`willows-grove` `governance/PROTECTED_AGENTS.md`,
-- blob `2886a41`; re-anchored 2026-09-11 — the earlier `c8c96b4` resolves nowhere reachable,
-- see docs/PART-III-READ.md), which cleared the first gate
-- and opened a better one: W-3's full clause is *"Between wards, default deny;
-- a crossing requires a guardian-signed envelope naming both lanes, purpose,
-- and expiry. A shared event is two lane entries with one referent."* The
-- twelve tables here encoded the first sentence and the third. The middle one
-- -- the clause's **permission** -- was absent, so a legitimate sibling
-- crossing was not merely ungated but unrepresentable: there was nowhere to
-- put the guardian's signature, the purpose or the expiry, and the only way to
-- serve a real case was to not record that it happened.
--
-- W-5 turned out to have the same shape, one axis over. Both are now tables.
--
-- ---------------------------------------------------------------------------
-- WHERE THE CONTENTS WENT. NON-AUTHORITATIVE -- this map is a finding aid, and
-- the successor is the fact. Anything below that disagrees with
-- migrations/001_lanes.sql is wrong, and this file is the defect.
--
--   twelve tables: person, lane, referent, lane_entry, scope_object, edge,
--   access_grant, declination, field_classification, disclosure_log,
--   consent_chain, reconciled_session
--       -> migrations/001_lanes.sql, unchanged in shape.
--
--   the append-only trigger over the three history tables
--       -> unchanged.
--
--   the classification seed
--       -> extended, not replaced: two tables' worth of columns added, and
--          the coverage assertion still runs both ways.
--
--   the comment above `edge` saying a self edge's holder "is NOT enforceable
--   here" and that a trigger was the answer "when this migration stops being
--   proposed"
--       -> it stopped being proposed. The trigger exists, and it refuses the
--          mirror row too: a ward holding guardian_of over its own lane.
--
--   ADDED at promotion, present in no version of this file:
--       crossing_envelope   -- W-3's permission
--       self_widening       -- W-5's per-matter widening of the self cap
--
-- ---------------------------------------------------------------------------
-- WHY THE STUB IS STILL HERE
--
-- Four documents and two modules cited this path by name -- docs/LANE-MODEL.md,
-- docs/EXIT.md, docs/RECONCILE-GUARDIAN.md, docs/FLEET-READS.md,
-- records/crossing.py, records/standing.py -- and the dated conformance records
-- under docs/conformance/ cite it as of the day they were written, which is
-- what makes them records. A path that simply vanishes turns every one of those
-- into §15's decayed citation, resolvable only by someone who already knows the
-- answer. The live pointers were updated; the dated ones cannot be, and this
-- file is what they land on.
--
-- It is also the honest form of the move. Deleting the old path would leave no
-- dated record that the DDL was ever proposed, which is refusal 3's argument
-- about guardianship applied to a file.
--
-- ---------------------------------------------------------------------------
-- Running this is a mistake, and it says so rather than succeeding quietly. A
-- stub of pure comments applies cleanly, prints nothing, and lets a reader
-- believe migration 001 has been applied -- which is rule 13's "absence
-- surfaces as unknown, never as a result" in the one place it would cost a
-- whole schema.

DO $$
BEGIN
    RAISE EXCEPTION
        'docs/schema/001_lanes.proposed.sql is a tombstone and declares nothing; '
        'apply migrations/001_lanes.sql instead (§16, rule 20)';
END;
$$;
